name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy-test:
    name: Deploy Test
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull Docker image
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/devops-demo:latest

      - name: Run container test
        run: |
          docker run -d -p 8080:80 \
          ${{ secrets.DOCKERHUB_USERNAME }}/devops-demo:latest

      - name: Check container
        run: |
          docker ps