name: CD

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed

permissions:
  contents: read

jobs:
  deploy:

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Ubuntu VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}

          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/devops-demo:latest

            docker stop devops-demo || true
            docker rm devops-demo || true

            docker run -d \
              --name devops-demo \
              --restart unless-stopped \
              -p 8080:80 \
              ${{ secrets.DOCKERHUB_USERNAME }}/devops-demo:latest
